import {
	bigint,
	date,
	foreignKey,
	index,
	numeric,
	pgTable,
	smallint,
	text,
	varchar,
} from "drizzle-orm/pg-core";
import { cfop } from "./cfop.js";
import { dav } from "./dav.js";
import { enquatramentoipi } from "./enquatramento-ipi.js";
import { produtos } from "./produtos.js";
import { receitasemcontribuicao } from "./receitasem-contribuicao.js";
import { unidademedida } from "./unidade-medida.js";
import { usuarios } from "./usuarios.js";

export const davitem = pgTable(
	"davitem",
	{
		id: text().primaryKey().notNull(),
		acrescimo: numeric({ precision: 12, scale: 2 }),
		acrescimoalteracao: numeric({ precision: 12, scale: 2 }),
		aliquota: numeric({ precision: 12, scale: 2 }),
		aliquotacofins: numeric({ precision: 12, scale: 4 }),
		aliquotacofinsincentivado: numeric({ precision: 12, scale: 2 }),
		aliquotacofinsretido: numeric({ precision: 5, scale: 2 }),
		aliquotafcpstanterior: numeric({ precision: 12, scale: 2 }),
		aliquotaicmsdesoneradosemdesc: numeric({ precision: 12, scale: 2 }),
		aliquotaicmsdiferencialentrada: numeric({ precision: 5, scale: 2 }),
		aliquotaicmsefetivo: numeric({ precision: 5, scale: 2 }),
		aliquotaicmsincentivado: numeric({ precision: 12, scale: 2 }),
		aliquotaicmspresumido: numeric({ precision: 5, scale: 2 }),
		aliquotaicmsstanterior: numeric({ precision: 12, scale: 2 }),
		aliquotaicmsstpresumido: numeric({ precision: 5, scale: 2 }),
		aliquotapis: numeric({ precision: 12, scale: 4 }),
		aliquotapisincentivado: numeric({ precision: 12, scale: 2 }),
		aliquotapisretido: numeric({ precision: 5, scale: 2 }),
		aliquotareducaobasecalculoinss: numeric({ precision: 12, scale: 2 }),
		altura: numeric({ precision: 10, scale: 2 }),
		basecalculoicmsdifal: numeric({ precision: 12, scale: 2 }),
		basecofins: numeric({ precision: 12, scale: 2 }),
		basecofinsretido: numeric({ precision: 12, scale: 2 }),
		basecontribuicaosocial: numeric({ precision: 12, scale: 2 }),
		basefcpstanterior: numeric({ precision: 5, scale: 2 }),
		basefundopobrezainterno: numeric({ precision: 12, scale: 2 }),
		basefundopobrezainternovirtual: numeric({ precision: 12, scale: 2 }),
		basefundopobrezast: numeric({ precision: 12, scale: 2 }),
		baseicms: numeric({ precision: 12, scale: 2 }),
		baseicmsdesoneradosemdesconto: numeric({ precision: 12, scale: 2 }),
		baseicmsdiferido: numeric({ precision: 12, scale: 2 }),
		baseicmsefetivo: numeric({ precision: 12, scale: 2 }),
		baseicmspresumido: numeric({ precision: 12, scale: 2 }),
		baseicmsstanterior: numeric({ precision: 12, scale: 2 }),
		baseicmsstpresumido: numeric({ precision: 12, scale: 2 }),
		baseicmssubstituicao: numeric({ precision: 12, scale: 2 }),
		baseicmsvirtual: numeric({ precision: 12, scale: 2 }),
		baseimpostoaproximado: numeric({ precision: 12, scale: 2 }),
		baseimpostoimportacao: numeric({ precision: 12, scale: 2 }),
		baseimpostorenda: numeric({ precision: 12, scale: 2 }),
		baseinss: numeric({ precision: 12, scale: 2 }),
		baseipi: numeric({ precision: 12, scale: 2 }),
		baseiss: numeric({ precision: 12, scale: 2 }),
		basepis: numeric({ precision: 12, scale: 2 }),
		basepisretido: numeric({ precision: 12, scale: 2 }),
		basestufdestino: numeric({ precision: 12, scale: 2 }),
		brinde: smallint(),
		cancelado: smallint(),
		cargatributariamedia: numeric({ precision: 12, scale: 2 }),
		chaveibpt: varchar({ length: 6 }),
		chavenferecebidaexportacao: varchar({ length: 44 }),
		codigobasedispenser: varchar({ length: 16 }),
		codigocordispenser: varchar({ length: 16 }),
		codigodav: bigint({ mode: "number" }),
		codigoembalagemdispenser: varchar({ length: 16 }),
		codigogrupodispenser: varchar({ length: 16 }),
		codigoorcamentodispenser: varchar({ length: 16 }),
		codigoproduto: varchar({ length: 20 }),
		codigoprodutodispenser: varchar({ length: 16 }),
		codigototalizadorparcial: varchar({ length: 7 }),
		cofins: numeric({ precision: 12, scale: 2 }),
		cofinsretido: numeric({ precision: 12, scale: 2 }),
		complementoitem: varchar({ length: 70 }),
		comprimento: numeric({ precision: 10, scale: 2 }),
		contador: smallint(),
		contribuicaosocial: numeric({ precision: 12, scale: 2 }),
		cstcofins: varchar({ length: 2 }),
		cstpis: varchar({ length: 2 }),
		currenttimemillis: bigint({ mode: "number" }),
		datainclusao: date(),
		dataorcamentodispenser: date(),
		decimaispreco: smallint(),
		decimaisquantidade: smallint(),
		deducaoicmsbasecofins: numeric({ precision: 12, scale: 2 }),
		deducaoicmsbasepis: numeric({ precision: 12, scale: 2 }),
		desconto: numeric({ precision: 12, scale: 2 }),
		descontoalteracao: numeric({ precision: 12, scale: 2 }),
		descontoclienteprodutoaplicado: smallint(),
		descontopromocao: numeric({ precision: 12, scale: 2 }),
		descontosubtotal: numeric({ precision: 12, scale: 2 }),
		descricaoarma: varchar({ length: 256 }),
		despesasaduaneiras: numeric({ precision: 12, scale: 2 }),
		enviartagsdiferimentototal: smallint(),
		fabricantedispenser: smallint(),
		fatorconversao: numeric({ precision: 15, scale: 6 }),
		fonteibpt: varchar({ length: 50 }),
		frete: numeric({ precision: 12, scale: 2 }),
		funrural: numeric({ precision: 12, scale: 2 }),
		hash: bigint({ mode: "number" }),
		hashpafnfce: bigint({ mode: "number" }),
		icms: numeric({ precision: 12, scale: 2 }),
		icmsdestino: numeric({ precision: 12, scale: 2 }),
		icmsdiferido: numeric({ precision: 12, scale: 2 }),
		icmsfundopobreza: numeric({ precision: 12, scale: 2 }),
		icmsfundopobrezainterno: numeric({ precision: 12, scale: 2 }),
		icmsfundopobrezainternovirtual: numeric({ precision: 12, scale: 2 }),
		icmsfundopobrezast: numeric({ precision: 12, scale: 2 }),
		icmsremetente: numeric({ precision: 12, scale: 2 }),
		icmssubstituicao: numeric({ precision: 12, scale: 2 }),
		icmsvirtual: numeric({ precision: 12, scale: 2 }),
		idajustedocumentofiscal: text(),
		idapontamentoproducaodispenser: text(),
		idcfop: text(),
		idcontribuicaosocialapurada: text(),
		idcontribuicaosocialapurcofins: text(),
		iddav: text().notNull(),
		idembalagem: text(),
		idembalagemtributavel: text(),
		idenquadramentoipi: text(),
		identidadedesconto: text(),
		idfilialretirada: text(),
		idflex: text(),
		iditemecommerce: varchar({ length: 20 }),
		iditemkitpai: text(),
		idlote: text(),
		idmotivodesconto: text(),
		idobservacaolancamentofiscal: text(),
		idproduto: text(),
		idprodutobase: text(),
		idprodutobrindepai: text(),
		idprodutokit: text(),
		idpromocao: text(),
		idpromocaoprazo: text(),
		idreceitasemcontribuicao: text(),
		idsupervisorvenda: text(),
		idtabelafinanciamento: text(),
		idtabelafinanciamentoprazo: text(),
		idtipocredito: text(),
		idunidademedida: text(),
		idunidademedidatributavel: text(),
		idusuariodesconto: text(),
		impostoaproximado: numeric({ precision: 12, scale: 2 }),
		impostoaproximadoestadual: numeric({ precision: 12, scale: 2 }),
		impostoaproximadofederal: numeric({ precision: 12, scale: 2 }),
		impostoaproximadomunicipal: numeric({ precision: 12, scale: 2 }),
		impostoimportacao: numeric({ precision: 12, scale: 2 }),
		impostorenda: numeric({ precision: 12, scale: 2 }),
		informacaoadicional: varchar({ length: 500 }),
		inss: numeric({ precision: 12, scale: 2 }),
		iof: numeric({ precision: 12, scale: 2 }),
		ipi: numeric({ precision: 12, scale: 2 }),
		ipinaodestacado: numeric({ precision: 12, scale: 2 }),
		iss: numeric({ precision: 12, scale: 2 }),
		largura: numeric({ precision: 10, scale: 2 }),
		margemvaloradicionado: numeric({ precision: 12, scale: 2 }),
		modalidadeicmsst: smallint(),
		modocalculoipi: smallint(),
		motivodesoneracaocofins: smallint(),
		motivodesoneracaoicms: smallint(),
		motivodesoneracaoicmssemdesc: smallint(),
		motivodesoneracaopis: smallint(),
		naoconsiderarvalortotalnota: smallint(),
		naopossuiicmsstnotaorigem: smallint(),
		nomeproduto: varchar({ length: 120 }),
		numeroitempedidocompra: varchar({ length: 6 }),
		numeropedidocliente: varchar({ length: 20 }),
		numeropedidocompra: varchar({ length: 15 }),
		numeroserie: varchar({ length: 40 }),
		numeroseriearma: varchar({ length: 15 }),
		numeroseriecanoarma: varchar({ length: 15 }),
		observacao: varchar({ length: 20 }),
		origem: smallint(),
		outrasdespesas: numeric({ precision: 12, scale: 2 }),
		pautapreco: smallint(),
		perccontribuicaosocial: numeric({ precision: 5, scale: 2 }),
		percentualdesconto: numeric({ precision: 12, scale: 2 }),
		percentualfunrural: numeric({ precision: 5, scale: 2 }),
		percentualicms: numeric({ precision: 5, scale: 2 }),
		percentualicmsaproveitamento: numeric({ precision: 7, scale: 4 }),
		percentualicmsdestino: numeric({ precision: 5, scale: 2 }),
		percentualicmsdiferido: numeric({ precision: 5, scale: 2 }),
		percentualicmsfundopobreza: numeric({ precision: 5, scale: 2 }),
		percentualicmsfundopobrezast: numeric({ precision: 5, scale: 2 }),
		percentualicmsinterestadual: numeric({ precision: 5, scale: 2 }),
		percentualicmssubstituicao: numeric({ precision: 5, scale: 2 }),
		percentualicmsvirtual: numeric({ precision: 5, scale: 2 }),
		percentualipi: numeric({ precision: 12, scale: 4 }),
		percentualipinaodestacado: numeric({ precision: 12, scale: 4 }),
		percentualiss: numeric({ precision: 7, scale: 4 }),
		percentualpartilhaicmsestados: numeric({ precision: 5, scale: 2 }),
		percentualredbaseicmsefetivo: numeric({ precision: 7, scale: 4 }),
		percentualreducaoicms: numeric({ precision: 9, scale: 6 }),
		percentualreducaoicmsdiferido: numeric({ precision: 5, scale: 2 }),
		percentualreducaoicmsvirtual: numeric({ precision: 9, scale: 6 }),
		percentualreducaoiss: numeric({ precision: 7, scale: 4 }),
		percentualreducaomva: numeric({ precision: 5, scale: 2 }),
		percentualretencaoiss: numeric({ precision: 7, scale: 4 }),
		percicmsfundopobinternovirtual: numeric({ precision: 5, scale: 2 }),
		percicmsfundopobrezainterno: numeric({ precision: 5, scale: 2 }),
		percimpostoaproximado: numeric({ precision: 5, scale: 2 }),
		percimpostoaproximadoestadual: numeric({ precision: 5, scale: 2 }),
		percimpostoaproximadofederal: numeric({ precision: 5, scale: 2 }),
		percimpostoaproximadomunicipal: numeric({ precision: 5, scale: 2 }),
		percimpostorenda: numeric({ precision: 5, scale: 2 }),
		percinss: numeric({ precision: 5, scale: 2 }),
		percredbasepiscofins: numeric({ precision: 5, scale: 2 }),
		percreducaoicmssubstituicao: numeric({ precision: 5, scale: 2 }),
		pis: numeric({ precision: 12, scale: 2 }),
		pisretido: numeric({ precision: 12, scale: 2 }),
		preco: numeric({ precision: 15, scale: 6 }),
		precominimovenda: numeric({ precision: 12, scale: 2 }),
		precooriginal: numeric({ precision: 15, scale: 6 }),
		quantidade: numeric({ precision: 15, scale: 6 }),
		quantidadepeca: bigint({ mode: "number" }),
		quantidadetributavel: numeric({ precision: 15, scale: 4 }),
		retencaoiss: numeric({ precision: 12, scale: 2 }),
		seguro: numeric({ precision: 12, scale: 2 }),
		situacaotributaria: varchar({ length: 7 }),
		situacaotributariaipi: varchar({ length: 3 }),
		situacaotributariasn: varchar({ length: 3 }),
		taxasiscomex: numeric({ precision: 12, scale: 2 }),
		tipoarma: smallint(),
		tipokit: smallint(),
		tipoprodutoespecifico: smallint(),
		tiporetiradaentregaitem: smallint(),
		tipotinta: smallint(),
		tipovalordesconto: smallint(),
		tipovaloricms: smallint(),
		tipovaloripi: smallint(),
		total: numeric({ precision: 12, scale: 2 }),
		tributacao: varchar({ length: 7 }),
		unidademedida: varchar({ length: 6 }),
		valorafrmm: numeric({ precision: 12, scale: 2 }),
		valorcofinsincentivado: numeric({ precision: 12, scale: 2 }),
		valorcomissao: numeric({ precision: 12, scale: 2 }),
		valordiferencaimportacaoxml: numeric({ precision: 12, scale: 2 }),
		valorfcpstanterior: numeric({ precision: 12, scale: 2 }),
		valorflex: numeric({ precision: 12, scale: 2 }),
		valoricmsaproveitamento: numeric({ precision: 12, scale: 2 }),
		valoricmsdesoneradosemdesconto: numeric({ precision: 12, scale: 2 }),
		valoricmsdiferencialentrada: numeric({ precision: 12, scale: 2 }),
		valoricmsefetivo: numeric({ precision: 12, scale: 2 }),
		valoricmsincentivado: numeric({ precision: 12, scale: 2 }),
		valoricmspresumido: numeric({ precision: 12, scale: 2 }),
		valoricmsstanterior: numeric({ precision: 12, scale: 2 }),
		valoricmsstpresumido: numeric({ precision: 12, scale: 2 }),
		valoricmssubstituto: numeric({ precision: 12, scale: 2 }),
		valorimpostosincentivados: numeric({ precision: 12, scale: 2 }),
		valorpauta: numeric({ precision: 12, scale: 2 }),
		valorpisincentivado: numeric({ precision: 12, scale: 2 }),
		valorstufdestino: numeric({ precision: 12, scale: 2 }),
		variacoes: varchar({ length: 4096 }),
		veiculonovo: smallint(),
	},
	(table) => [
		index("davitem_iddav_idx").using(
			"btree",
			table.iddav.asc().nullsLast().op("text_ops"),
		),
		index("davitem_idproduto_idx").using(
			"btree",
			table.idproduto.asc().nullsLast().op("text_ops"),
		),
		foreignKey({
			columns: [table.iddav],
			foreignColumns: [dav.id],
			name: "fk_davitem_dav",
		})
			.onUpdate("cascade")
			.onDelete("cascade"),
		foreignKey({
			columns: [table.idproduto],
			foreignColumns: [produtos.id],
			name: "fk_davitem_produto",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idprodutokit],
			foreignColumns: [produtos.id],
			name: "fk_davitem_produtokit",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idusuariodesconto],
			foreignColumns: [usuarios.id],
			name: "fk_davitem_usuariodesconto",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idsupervisorvenda],
			foreignColumns: [usuarios.id],
			name: "fk_davitem_usuariopreco",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idcfop],
			foreignColumns: [cfop.id],
			name: "fk_davitem_cfop",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idenquadramentoipi],
			foreignColumns: [enquatramentoipi.id],
			name: "fk_davitem_enqipi",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idunidademedida],
			foreignColumns: [unidademedida.id],
			name: "fk_davitem_unidademedida",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idunidademedidatributavel],
			foreignColumns: [unidademedida.id],
			name: "fk_davitem_unidademedida_trib",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idreceitasemcontribuicao],
			foreignColumns: [receitasemcontribuicao.id],
			name: "fk_davitem_receitasemcontribuicao",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.iditemkitpai],
			foreignColumns: [table.id],
			name: "fk_davitem_itemkitpai",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
	],
);
