import {
	bigint,
	char,
	date,
	foreignKey,
	index,
	jsonb,
	numeric,
	pgTable,
	smallint,
	text,
	timestamp,
	varchar,
} from "drizzle-orm/pg-core";
import { cfop } from "./cfop.js";
import { motivorebaixa } from "./motivo-rebaixa.js";
import { ncm } from "./ncm.js";
import { notafiscal } from "./nota-fiscal.js";
import { produtos } from "./produtos.js";
import { unidademedida } from "./unidade-medida.js";
import { usuarios } from "./usuarios.js";

export const notafiscalitem = pgTable(
	"notafiscalitem",
	{
		id: text().primaryKey().notNull(),
		acrescimo: numeric({ precision: 12, scale: 2, mode: "string" }),
		aliquotacofins: numeric({ precision: 12, scale: 4, mode: "string" }),
		aliquotacofinsretido: numeric({ precision: 5, scale: 2, mode: "string" }),
		altura: numeric({ precision: 10, scale: 2, mode: "string" }),
		anofabricacao: smallint(),
		anomodelofabricacao: smallint(),
		aplicaprecocalculado: smallint(),
		cfop: varchar({ length: 20 }),
		chassi: varchar({ length: 17 }),
		chaveibpt: varchar({ length: 6 }),
		chavenfe: varchar({ length: 44 }),
		chavenferecebidaexportacao: varchar({ length: 44 }),
		cilindrada: varchar({ length: 4 }),
		classificacaofiscal: varchar({ length: 8 }),
		cm3: varchar({ length: 4 }),
		cmkg: varchar({ length: 9 }),
		cmvatual: numeric({ precision: 15, scale: 6, mode: "string" }),
		cnpjconcessionaria: varchar({ length: 18 }),
		cnpjemissor: varchar({ length: 14 }),
		codigobeneficiofiscal: varchar({ length: 10 }),
		codigolistalc11603: varchar({ length: 5 }),
		codigomarcamodelo: numeric({ precision: 7, scale: 0, mode: "string" }),
		condicaoveiculo: smallint(),
		contador: smallint(),
		cor: varchar({ length: 4 }),
		cordenatran: varchar({ length: 2 }),
		cstcofins: varchar({ length: 2 }),
		cstpis: varchar({ length: 2 }),
		currenttimemillis: bigint({ mode: "number" }),
		datahoraretirada: timestamp({ precision: 3, mode: "string" }),
		datalote: date(),
		datavalidade: date(),
		dataprogramacaopreco: date(),
		decimaispreco: smallint(),
		decimaisquantidade: smallint(),
		descontoclienteprodutoaplicado: smallint(),
		descricao: varchar({ length: 120 }),
		descricaoarma: varchar({ length: 256 }),
		descricaocor: varchar({ length: 40 }),
		detalhenfe: text(),
		distanciaeixos: varchar({ length: 4 }),
		emissao: date(),
		entidadenotafiscalterceiros: varchar({ length: 60 }),
		enviartagsdiferimentototal: smallint(),
		especieveiculo: smallint(),
		fonteibpt: varchar({ length: 50 }),
		gerarcreditoicmsst: smallint(),
		gerarcreditoipi: smallint(),
		hash: bigint({ mode: "number" }),
		icmsstinformadomanualmente: smallint(),
		idajustedocumentofiscal: text(),
		idativoimobilizado: text(),
		idbasecalculocredito: text(),
		idbeneficiofiscal: text(),
		idcfop: text(),
		idcontribuicaosocialapurada: text(),
		idcontribuicaosocialapurcofins: text(),
		iddavitem: text(),
		iddevolucaoitem: text(),
		idembalagem: text(),
		idembalagemtributavel: text(),
		idenquadramentoipi: text(),
		identidadedesconto: text(),
		idestadoconcessionaria: text(),
		idfilialretiradaentrega: text(),
		idlote: text(),
		idmotivodesconto: text(),
		idmotivorebaixa: text(),
		idncm: text(),
		idnotafiscal: text().notNull(),
		idnotafiscalitemdevolvido: text(),
		idnotafiscalitemterceiros: text(),
		idnotafiscalitemtranscompra: text(),
		idnotafiscalitemtransfsaida: text(),
		idobservacaolancamentofiscal: text(),
		idpedidocompraitem: text(),
		idproduto: text(),
		idprodutobase: text(),
		idprodutokit: text(),
		idpromocao: text(),
		idreceitasemcontribuicao: text(),
		idrepresentante2: text(),
		idrequisicaotransferenciaitem: text(),
		idsupervisorvenda: text(),
		idtipocredito: text(),
		idunidademedida: text(),
		idunidademedidatributavel: text(),
		idusuariodesconto: text(),
		idusuarioretirada: text(),
		informacaoadicional: varchar({ length: 500 }),
		itemorigempossuicofins: smallint(),
		itemorigempossuiicms: smallint(),
		itemorigempossuiipi: smallint(),
		itemorigempossuipis: smallint(),
		itempeps: smallint(),
		lotacao: smallint(),
		lote: varchar({ length: 30 }),
		marcaveiculo: varchar({ length: 20 }),
		modalidadeicmsst: smallint(),
		modocalculoipi: smallint(),
		modocalculopreco: smallint(),
		motivodesoneracaocofins: smallint(),
		motivodesoneracaoicms: smallint(),
		motivodesoneracaoicmssemdesc: smallint(),
		motivodesoneracaopis: smallint(),
		naoconsiderarvalortotalnota: smallint(),
		naopossuiicmsstnotaorigem: smallint(),
		ncm: varchar({ length: 11 }),
		numerodrawback: varchar({ length: 20 }),
		numeroitempedidocompra: varchar({ length: 6 }),
		numeromotor: varchar({ length: 21 }),
		numeronotafiscal: varchar({ length: 11 }),
		numeronotafiscalterceiros: varchar({ length: 11 }),
		numeropedidocompra: varchar({ length: 15 }),
		numeroregistroexportacao: varchar({ length: 12 }),
		numeroseriearma: varchar({ length: 15 }),
		numeroseriecanoarma: varchar({ length: 15 }),
		observacao: varchar({ length: 20 }),
		observacaorebaixa: text(),
		origem: smallint(),
		pautapreco: smallint(),
		percentualicmsaproveitamento: numeric({ precision: 7, scale: 4, mode: "string" }),
		percentualreducaoicms: numeric({ precision: 9, scale: 6, mode: "string" }),
		pesobrutoveiculo: varchar({ length: 9 }),
		pesoliquidoveiculo: varchar({ length: 9 }),
		placaveiculo: varchar({ length: 8 }),
		potenciamotor: varchar({ length: 4 }),
		precificado: smallint(),
		produto: varchar({ length: 20 }),
		produtoespecifico: smallint(),
		quantidadehora: varchar({ length: 5 }),
		quantidadepeca: bigint({ mode: "number" }),
		quantidadetributavel: numeric({ precision: 15, scale: 4, mode: "string" }),
		referenciafornecedor: varchar({ length: 60 }),
		renavam: varchar({ length: 11 }),
		replicarcusto: smallint(),
		replicarformacao: smallint(),
		reterpiscofins: smallint(),
		retirado: smallint(),
		serial: varchar({ length: 9 }),
		serie: varchar({ length: 4 }),
		situacaotributaria: varchar({ length: 3 }),
		situacaotributariadigitada: varchar({ length: 3 }),
		situacaotributariaipi: varchar({ length: 3 }),
		situacaotributariasn: varchar({ length: 3 }),
		statusprecoitem: smallint(),
		statusremessaterceiros: smallint(),
		tipo: char({ length: 1 }),
		tipoarma: smallint(),
		tipocombustivel: varchar({ length: 8 }),
		tipodocumentopaf: varchar({ length: 1 }),
		tipokit: smallint(),
		tipooperacao: smallint(),
		tipopintura: varchar({ length: 1 }),
		tiporestricao: smallint(),
		tiporetiradaentregaitem: smallint(),
		tipotinta: smallint(),
		tipovalordesconto: smallint(),
		tipovaloricms: smallint(),
		tipovaloripi: smallint(),
		tipoveiculo: smallint(),
		totalizadorparcial: varchar({ length: 10 }),
		tributacao: varchar({ length: 7 }),
		tributacaoespecial: varchar({ length: 7 }),
		unidade: varchar({ length: 6 }),
		unidademedidaxml: varchar({ length: 6 }),
		veiculonovo: smallint(),
		vim: varchar({ length: 1 }),
		quantidade: numeric({ precision: 15, scale: 6, mode: "string" }),
		precounitario: numeric({ precision: 15, scale: 6, mode: "string" }),
		total: numeric({ precision: 12, scale: 2, mode: "string" }),
		desconto: numeric({ precision: 12, scale: 2, mode: "string" }),
		baseicms: numeric({ precision: 12, scale: 2, mode: "string" }),
		percentualicms: numeric({ precision: 5, scale: 2, mode: "string" }),
		icms: numeric({ precision: 12, scale: 2, mode: "string" }),
		aliquotapis: numeric({ precision: 12, scale: 4, mode: "string" }),
		pis: numeric({ precision: 12, scale: 2, mode: "string" }),
		cofins: numeric({ precision: 12, scale: 2, mode: "string" }),
		ipi: numeric({ precision: 12, scale: 2, mode: "string" }),
		custoaquisicao: numeric({ precision: 15, scale: 6, mode: "string" }),
		frete: numeric({ precision: 12, scale: 2, mode: "string" }),
		seguro: numeric({ precision: 12, scale: 2, mode: "string" }),
		outrasdespesas: numeric({ precision: 12, scale: 2, mode: "string" }),
		pisretido: numeric({ precision: 12, scale: 2, mode: "string" }),
		cofinsretido: numeric({ precision: 12, scale: 2, mode: "string" }),
		inss: numeric({ precision: 12, scale: 2, mode: "string" }),
		dadosimportacao: jsonb(),
	},
	(table) => [
		index("notafiscalitem_idnotafiscal_idx").using(
			"btree",
			table.idnotafiscal.asc().nullsLast().op("text_ops"),
		),
		index("notafiscalitem_idproduto_idx").using(
			"btree",
			table.idproduto.asc().nullsLast().op("text_ops"),
		),
		foreignKey({
			columns: [table.idnotafiscal],
			foreignColumns: [notafiscal.id],
			name: "fk_notafiscalitem_notafiscal",
		})
			.onUpdate("cascade")
			.onDelete("cascade"),
		foreignKey({
			columns: [table.idproduto],
			foreignColumns: [produtos.id],
			name: "fk_notafiscalitem_produto",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idprodutokit],
			foreignColumns: [produtos.id],
			name: "fk_notafiscalitem_produtokit",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idcfop],
			foreignColumns: [cfop.id],
			name: "fk_notafiscalitem_cfop",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idncm],
			foreignColumns: [ncm.id],
			name: "fk_nfitem_ncm",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idunidademedida],
			foreignColumns: [unidademedida.id],
			name: "fk_nfitem_unidademedida",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idunidademedidatributavel],
			foreignColumns: [unidademedida.id],
			name: "fk_nfitem_unidademedida_trib",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idmotivorebaixa],
			foreignColumns: [motivorebaixa.id],
			name: "fk_notafiscalitem_motrebaixa",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idusuariodesconto],
			foreignColumns: [usuarios.id],
			name: "fk_nfitem_usuariodesconto",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idsupervisorvenda],
			foreignColumns: [usuarios.id],
			name: "fk_nfitem_usuariopreco",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idusuarioretirada],
			foreignColumns: [usuarios.id],
			name: "fk_nfitem_usuario_retirada",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idnotafiscalitemterceiros],
			foreignColumns: [table.id],
			name: "fk_nfitem_nfi_terc",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idnotafiscalitemdevolvido],
			foreignColumns: [table.id],
			name: "fk_nfitem_nfi_dev",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
	],
);
