import {
	bigint,
	char,
	date,
	foreignKey,
	index,
	integer,
	jsonb,
	numeric,
	pgTable,
	smallint,
	text,
	time,
	timestamp,
	varchar,
} from "drizzle-orm/pg-core";
import { cfop } from "./cfop.js";
import { condicaopagamento } from "./condicao-pagamento.js";
import { contacorrente } from "./conta-corrente.js";
import { empresa } from "./empresas.js";
import { entidade } from "./entidade.js";
import { localretirada } from "./local-retirada.js";
import { operacaofiscal } from "./operacao-fiscal.js";
import { planocontas } from "./plano-contas.js";
import { tipodocumentofinanceiro } from "./tipo-documento-financeiro.js";
import { usuarios } from "./usuarios.js";

export const notafiscal = pgTable(
	"notafiscal",
	{
		id: text().primaryKey().notNull(),
		idempresa: text().notNull(),
		acrescimocancelamento: numeric({ precision: 12, scale: 2 }),
		acrescimoservicos: numeric({ precision: 12, scale: 2 }),
		acrescimosproduto: numeric({ precision: 12, scale: 2 }),
		acrescimosubtotal: numeric({ precision: 12, scale: 2 }),
		agenciabancocheque: varchar({ length: 10 }),
		aliquotacofinsconhecimento: numeric({ precision: 12, scale: 2 }),
		aliquotaicms: numeric({ precision: 12, scale: 2 }),
		aliquotapisconhecimento: numeric({ precision: 12, scale: 2 }),
		alterado: smallint(),
		aprazo: numeric({ precision: 12, scale: 2 }),
		arquivoxmlassinado: text(),
		arquivoxmlautorizada: text(),
		arquivoxmlcancelada: text(),
		arquivoxmlconsultasituacao: text(),
		arquivoxmlcontingencia: text(),
		arquivoxmldenegada: text(),
		arquivoxmleventoepec: text(),
		arquivoxmlnotaoriginal: text(),
		avista: numeric({ precision: 12, scale: 2 }),
		bairro: varchar({ length: 50 }),
		bairroentrega: varchar({ length: 50 }),
		bairroobra: varchar({ length: 60 }),
		basecalculoicmsdifal: numeric({ precision: 12, scale: 2 }),
		basecofinsretido: numeric({ precision: 12, scale: 2 }),
		basecontribuicaosocial: numeric({ precision: 12, scale: 2 }),
		basefcpstanterior: numeric({ precision: 12, scale: 2 }),
		baseicms: numeric({ precision: 12, scale: 2 }),
		baseicmsdiferido: numeric({ precision: 12, scale: 2 }),
		baseicmsefetivo: numeric({ precision: 12, scale: 2 }),
		baseicmsnaoaproveitado: numeric({ precision: 12, scale: 2 }),
		baseicmsstanterior: numeric({ precision: 12, scale: 2 }),
		baseicmssubstituicao: numeric({ precision: 12, scale: 2 }),
		baseimpostorenda: numeric({ precision: 12, scale: 2 }),
		baseinss: numeric({ precision: 12, scale: 2 }),
		baseiss: numeric({ precision: 12, scale: 2 }),
		basepiscofinsconhecimento: numeric({ precision: 12, scale: 2 }),
		basepisretido: numeric({ precision: 12, scale: 2 }),
		canceladoporevento: smallint(),
		cancelamento: timestamp({ precision: 3, mode: "string" }),
		carteiradigital: numeric({ precision: 12, scale: 2 }),
		celularentrega: varchar({ length: 40 }),
		cep: varchar({ length: 9 }),
		cepentrega: varchar({ length: 9 }),
		cepobra: varchar({ length: 9 }),
		cfopconhecimentotransporte: varchar({ length: 5 }),
		chavedocumentoreferenciado: varchar({ length: 44 }),
		chavenfe: varchar({ length: 44 }),
		cheque: numeric({ precision: 12, scale: 2 }),
		cidade: varchar({ length: 50 }),
		cidadetransportadora: varchar({ length: 50 }),
		classeconsumoagua: varchar({ length: 2 }),
		classeconsumocomunicacao: varchar({ length: 2 }),
		classeconsumoenergia: varchar({ length: 2 }),
		classeconsumogas: varchar({ length: 2 }),
		cnpjcpf: varchar({ length: 20 }),
		cnpjcpfentrega: varchar({ length: 18 }),
		cnpjcpftransportadora: varchar({ length: 18 }),
		cnpjemissor: varchar({ length: 14 }),
		codigoantecipacaotributaria: smallint(),
		codigoautenticidadenfse: varchar({ length: 255 }),
		codigoexportador: varchar({ length: 60 }),
		codigostatusprotocolonfe: smallint(),
		codigostatustransmissaonfe: smallint(),
		cofins: numeric({ precision: 12, scale: 2 }),
		cofinsretido: numeric({ precision: 12, scale: 2 }),
		complemento: varchar({ length: 50 }),
		complementoentrega: varchar({ length: 60 }),
		complementolocalobra: varchar({ length: 255 }),
		conferencia: smallint(),
		conferenciafinanceira: smallint(),
		conferenciafisica: smallint(),
		consignacaogerada: smallint(),
		consumidorfinal: smallint(),
		consumoagua: varchar({ length: 2 }),
		consumoenergia: varchar({ length: 2 }),
		contrato: varchar({ length: 60 }),
		contribuicaosocial: numeric({ precision: 12, scale: 2 }),
		coodocumentoreferenciado: integer(),
		cpfcnpjautorizadoxml: varchar({ length: 20 }),
		cpfcnpjemitentecheque: varchar({ length: 20 }),
		csticmsconhecimento: varchar({ length: 3 }),
		csticmssnconhecimento: varchar({ length: 3 }),
		cstpiscofinsconhecimento: varchar({ length: 2 }),
		currenttimemillis: bigint({ mode: "number" }),
		dadosimportacao: jsonb(),
		dataalteracao: timestamp({ precision: 3, mode: "string" }),
		dataconfcega: timestamp({ precision: 3, mode: "string" }),
		dataconffinanceira: timestamp({ precision: 3, mode: "string" }),
		datacontingencia: varchar({ length: 10 }),
		datadesembaraco: date(),
		datadi: date(),
		datadocumentoreferenciado: date(),
		dataemissaonotaprodutor: date(),
		dataextemporanea: date(),
		datahoraconsultasituacao: timestamp({ precision: 3, mode: "string" }),
		datahoraemissao: timestamp({ precision: 3, mode: "string" }),
		datahoraentradasaida: timestamp({ precision: 3, mode: "string" }),
		datahoransu: timestamp({ precision: 3, mode: "string" }),
		datainclusao: timestamp({ precision: 3, mode: "string" }),
		datapedido: date(),
		datapreparacao: date(),
		datavencimentocontrato: date(),
		deposito: numeric({ precision: 12, scale: 2 }),
		descontoproduto: numeric({ precision: 12, scale: 2 }),
		descontoservicos: numeric({ precision: 12, scale: 2 }),
		descontosubtotal: numeric({ precision: 12, scale: 2 }),
		descricaocfop: varchar({ length: 1024 }),
		despesasimportacao: numeric({ precision: 12, scale: 2 }),
		devolucao: numeric({ precision: 12, scale: 2 }),
		devolucaoautomatica: smallint(),
		diafaturamentocontrato: smallint(),
		dinheiro: numeric({ precision: 12, scale: 2 }),
		documentoorigem: bigint({ mode: "number" }),
		ecfseriedocumentoreferenciado: varchar({ length: 20 }),
		emailentrega: varchar({ length: 60 }),
		emissao: date(),
		endereco: varchar({ length: 60 }),
		enderecoentrega: varchar({ length: 60 }),
		enderecotransportadora: varchar({ length: 50 }),
		entradasaida: date(),
		especie: varchar({ length: 60 }),
		estado: char({ length: 2 }),
		estadotransportadora: char({ length: 2 }),
		estadoveiculo: char({ length: 2 }),
		extra: numeric({ precision: 12, scale: 2 }),
		finalidadeemissaonfe: smallint(),
		financiado: numeric({ precision: 12, scale: 2 }),
		formaemissaonfe: smallint(),
		formaintermedioimportacao: smallint(),
		frete: numeric({ precision: 12, scale: 2 }),
		funrural: numeric({ precision: 12, scale: 2 }),
		hash: bigint({ mode: "number" }),
		horacontingencia: varchar({ length: 8 }),
		horasaida: time(),
		icms: numeric({ precision: 12, scale: 2 }),
		icmsdestino: numeric({ precision: 12, scale: 2 }),
		icmsdiferido: numeric({ precision: 12, scale: 2 }),
		icmsfundopobreza: numeric({ precision: 12, scale: 2 }),
		icmsfundopobrezainterno: numeric({ precision: 12, scale: 2 }),
		icmsfundopobrezainternonaoapro: numeric({ precision: 12, scale: 2 }),
		icmsfundopobrezast: numeric({ precision: 12, scale: 2 }),
		icmsnaoaproveitado: numeric({ precision: 12, scale: 2 }),
		icmsremetente: numeric({ precision: 12, scale: 2 }),
		icmssubstituicao: numeric({ precision: 12, scale: 2 }),
		idadmcarteiradigital: text(),
		idbancocheque: text(),
		idbasecalculocredito: text(),
		idbeneficiador: text(),
		idcfop: text(),
		idcidade: text(),
		idcidadedestinoconhec: text(),
		idcidadeentrega: text(),
		idcidadeobra: text(),
		idcidadeorigemconhec: text(),
		idcidadeprestacaoservico: text(),
		idcidadetransportadora: text(),
		idclientedobeneficiador: text(),
		idcondicaopagto: text(),
		idcontacorrentedeposito: text(),
		idcontacorrentepix: text(),
		iddocumentoconsignacao: text(),
		identidade: text(),
		identidadefilialanterior: text(),
		idestado: text(),
		idestadodesembaraco: text(),
		idestadodestinoconhec: text(),
		idestadoentrega: text(),
		idestadoobra: text(),
		idestadoorigemconhec: text(),
		idestadoprestacaoservico: text(),
		idestadosaidapais: text(),
		idestadotransportadora: text(),
		idestadoveiculo: text(),
		idfilial: text(),
		idintermediadormarketplace: text(),
		idlocalestoque: text(),
		idlocalestoqueentradatransf: text(),
		idlocalestoquesaidatransf: text(),
		idlocalretirada: text(),
		idmotivodesconto: text(),
		idnotadesagregacaoinsumos: text(),
		idnotaentradaconsignacao: text(),
		idnotafiscaltransfdestino: text(),
		idnotafiscalvendaexpedicao: text(),
		idnotarelacionadaconhecimento: text(),
		idoperacao: text(),
		idoperacaofiscal: text(),
		idpais: text(),
		idplanocontas: text(),
		idrepresentante: text(),
		idrepresentante2: text(),
		idserie: text(),
		idtipocredito: text(),
		idtipodocumento: text(),
		idtransacaofinanceira: text(),
		idtransportadora: text(),
		idusuarioalteracao: text(),
		idusuarioconfcega: text(),
		idusuarioconffinanceira: text(),
		idusuarioinclusao: text(),
		idusuarioliberouatraso: text(),
		idusuarioliberoulimite: text(),
		ietransportadora: varchar({ length: 20 }),
		impostoaproximado: numeric({ precision: 12, scale: 2 }),
		impostoimportacao: numeric({ precision: 12, scale: 2 }),
		impostorenda: numeric({ precision: 12, scale: 2 }),
		impresso: smallint(),
		indacrescimosubtotal: varchar({ length: 1 }),
		inddescontosubtotal: varchar({ length: 1 }),
		indicadornaturezafrete: smallint(),
		infocompgerada: text(),
		infocomppersonalizada: text(),
		infofisco: text(),
		infofiscogerada: text(),
		inscricaoestadual: varchar({ length: 20 }),
		inss: numeric({ precision: 12, scale: 2 }),
		ipi: numeric({ precision: 12, scale: 2 }),
		iss: numeric({ precision: 12, scale: 2 }),
		justificativacancelamentonfe: varchar({ length: 255 }),
		latitude: numeric({ precision: 10, scale: 7 }),
		latitudeentrega: numeric({ precision: 10, scale: 7 }),
		linknfse: varchar({ length: 255 }),
		localdesembaraco: varchar({ length: 60 }),
		localdespacho: varchar({ length: 60 }),
		localsaidapais: varchar({ length: 60 }),
		logradouroobra: varchar({ length: 255 }),
		longitude: numeric({ precision: 10, scale: 7 }),
		longitudeentrega: numeric({ precision: 10, scale: 7 }),
		marca: varchar({ length: 60 }),
		mediaaliquotacofinsincentivado: numeric({ precision: 12, scale: 2 }),
		mediaaliquotaicmsincentivado: numeric({ precision: 12, scale: 2 }),
		mediaaliquotapisincentivado: numeric({ precision: 12, scale: 2 }),
		mensagemprotocolonfe: text(),
		mensagemtransmissaonfe: text(),
		modelo: varchar({ length: 4 }),
		modelodocumentoreferenciado: varchar({ length: 10 }),
		modelonotaprodutor: varchar({ length: 2 }),
		motivocontingencia: varchar({ length: 256 }),
		nomeemitentecheque: varchar({ length: 60 }),
		nometransportadora: varchar({ length: 60 }),
		notadesagregacaoinsumos: smallint(),
		notaempenho: varchar({ length: 22 }),
		nsu: integer(),
		numero: varchar({ length: 60 }),
		numeroart: varchar({ length: 20 }),
		numerocei: varchar({ length: 20 }),
		numerocheque: varchar({ length: 20 }),
		numerocontacorrentebancocheque: varchar({ length: 10 }),
		numerodi: varchar({ length: 12 }),
		numerodocumentoreferenciado: varchar({ length: 11 }),
		numerodrawback: varchar({ length: 20 }),
		numeroendereco: varchar({ length: 6 }),
		numeroenderecoentrega: varchar({ length: 6 }),
		numeroenderecotransportadora: varchar({ length: 6 }),
		numerolotecancelamento: integer(),
		numeroloteenvio: integer(),
		numeromatricula: varchar({ length: 20 }),
		numeronfse: varchar({ length: 20 }),
		numeronotafiscal: varchar({ length: 11 }),
		numeronotaprodutor: varchar({ length: 9 }),
		numeroobra: varchar({ length: 20 }),
		numeroprojeto: varchar({ length: 20 }),
		numeroserienotaprodutor: varchar({ length: 3 }),
		observacao: text(),
		ordemdescontoacrescimo: varchar({ length: 1 }),
		origemprincipal: integer(),
		outrasdespesas: numeric({ precision: 12, scale: 2 }),
		outros: numeric({ precision: 12, scale: 2 }),
		pautapreco: smallint(),
		pdvdocumentoreferenciado: smallint(),
		pedido: varchar({ length: 60 }),
		pendenciarps: smallint(),
		percentualcomissaofaturamento: numeric({ precision: 5, scale: 2 }),
		percentualcomissaofaturamento2: numeric({ precision: 5, scale: 2 }),
		percentualcomissaoquitacao: numeric({ precision: 5, scale: 2 }),
		percentualcomissaoquitacao2: numeric({ precision: 5, scale: 2 }),
		percentualdescontosubtotal: numeric({ precision: 5, scale: 2 }),
		percentualredbaseicmsconhec: numeric({ precision: 5, scale: 2 }),
		pesobruto: numeric({ precision: 12, scale: 3 }),
		pesoliquido: numeric({ precision: 12, scale: 3 }),
		pis: numeric({ precision: 12, scale: 2 }),
		pisretido: numeric({ precision: 12, scale: 2 }),
		pix: numeric({ precision: 12, scale: 2 }),
		placaveiculo: varchar({ length: 8 }),
		posaprazo: numeric({ precision: 12, scale: 2 }),
		posavista: numeric({ precision: 12, scale: 2 }),
		possuicartacorrecao: smallint(),
		precopendente: smallint(),
		presencaconsumidor: smallint(),
		proprio: smallint(),
		protocoloepec: varchar({ length: 50 }),
		protocolonfe: varchar({ length: 18 }),
		quantidade: numeric({ precision: 15, scale: 6 }),
		razaosocial: varchar({ length: 60 }),
		razaosocialnomeentrega: varchar({ length: 60 }),
		recebimentonfe: varchar({ length: 30 }),
		recibotransmissaonfe: varchar({ length: 18 }),
		retencaoiss: numeric({ precision: 12, scale: 2 }),
		seguro: numeric({ precision: 12, scale: 2 }),
		serie: varchar({ length: 6 }),
		seriedocumentoreferenciado: varchar({ length: 6 }),
		status: smallint(),
		statusconsignacaoentrada: smallint(),
		statusdesagregacao: char({ length: 1 }),
		taxasiscomex: numeric({ precision: 12, scale: 2 }),
		telefone: varchar({ length: 40 }),
		telefoneentrega: varchar({ length: 40 }),
		tipoambientenfe: smallint(),
		tipoassinante: varchar({ length: 2 }),
		tipocontribuinte: smallint(),
		tipocte: varchar({ length: 2 }),
		tipodocumento: varchar({ length: 2 }),
		tipodocumentoconsignacao: smallint(),
		tipodocumentoimportacao: smallint(),
		tipodocumentopaf: varchar({ length: 1 }),
		tipoemissao: char({ length: 1 }),
		tipofrete: smallint(),
		tipoligacao: varchar({ length: 2 }),
		tiponotadocumentoreferenciado: varchar({ length: 3 }),
		tipoorigem: smallint(),
		tiporateiocentrocusto: smallint(),
		tiporateioconhecimento: smallint(),
		tipotelefone: smallint(),
		tipotensao: varchar({ length: 2 }),
		tipoviatransporteinternacional: smallint(),
		totalproduto: numeric({ precision: 12, scale: 2 }),
		totalservicos: numeric({ precision: 12, scale: 2 }),
		transferencia: smallint(),
		transferenciaentradaautomatica: smallint(),
		valorafrmm: numeric({ precision: 12, scale: 2 }),
		valorcofinsincentivado: numeric({ precision: 12, scale: 2 }),
		valorfcpstanterior: numeric({ precision: 12, scale: 2 }),
		valoricmsdesoneradosemdesconto: numeric({ precision: 12, scale: 2 }),
		valoricmsefetivo: numeric({ precision: 12, scale: 2 }),
		valoricmsincentivado: numeric({ precision: 12, scale: 2 }),
		valoricmsstanterior: numeric({ precision: 12, scale: 2 }),
		valorimpostosincentivados: numeric({ precision: 12, scale: 2 }),
		valorpisincentivado: numeric({ precision: 12, scale: 2 }),
		valortotalnota: numeric({ precision: 12, scale: 2 }),
		valorvendor: numeric({ precision: 12, scale: 2 }),
		vencimentocheque: date(),
	},
	(table) => [
		index("notafiscal_idempresa_idx").using(
			"btree",
			table.idempresa.asc().nullsLast().op("text_ops"),
		),
		index("notafiscal_identidade_idx").using(
			"btree",
			table.identidade.asc().nullsLast().op("text_ops"),
		),
		index("notafiscal_idfilial_idx").using(
			"btree",
			table.idfilial.asc().nullsLast().op("text_ops"),
		),
		index("notafiscal_chavenfe_idx").using(
			"btree",
			table.chavenfe.asc().nullsLast().op("text_ops"),
		),
		foreignKey({
			columns: [table.idempresa],
			foreignColumns: [empresa.id],
			name: "fk_notafiscal_empresa",
		})
			.onUpdate("cascade")
			.onDelete("cascade"),
		foreignKey({
			columns: [table.identidade],
			foreignColumns: [entidade.id],
			name: "fk_notafiscal_entidade",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idrepresentante],
			foreignColumns: [entidade.id],
			name: "fk_notafiscal_representante",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idrepresentante2],
			foreignColumns: [entidade.id],
			name: "fk_notafiscal_representante2",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idcfop],
			foreignColumns: [cfop.id],
			name: "fk_notafiscal_cfop",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idtransportadora],
			foreignColumns: [entidade.id],
			name: "fk_notafiscal_transportadora",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idcondicaopagto],
			foreignColumns: [condicaopagamento.id],
			name: "fk_notafiscal_condicaopag",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idtipodocumento],
			foreignColumns: [tipodocumentofinanceiro.id],
			name: "fk_notafiscal_tipdocfinanceiro",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idusuarioinclusao],
			foreignColumns: [usuarios.id],
			name: "fk_notafiscal_usuarioinclusao",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idusuarioalteracao],
			foreignColumns: [usuarios.id],
			name: "fk_notafiscal_usuarioalteracao",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idnotarelacionadaconhecimento],
			foreignColumns: [table.id],
			name: "fk_notafiscal_notafiscalconhec",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idnotaentradaconsignacao],
			foreignColumns: [table.id],
			name: "fk_notafiscal_nfentradaconsig",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idoperacaofiscal],
			foreignColumns: [operacaofiscal.id],
			name: "fk_notafiscal_operacaofiscal",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idusuarioconffinanceira],
			foreignColumns: [usuarios.id],
			name: "fk_notafiscal_usuarioconffin",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idusuarioconfcega],
			foreignColumns: [usuarios.id],
			name: "fk_notafiscal_usuarioconfcega",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idnotadesagregacaoinsumos],
			foreignColumns: [table.id],
			name: "fk_notafiscal_nfentradadesins",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idbeneficiador],
			foreignColumns: [entidade.id],
			name: "fk_entidade_beneficiador",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idclientedobeneficiador],
			foreignColumns: [entidade.id],
			name: "fk_entidade_cliente_benef",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idnotafiscaltransfdestino],
			foreignColumns: [table.id],
			name: "fk_nf_nftransf",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idnotafiscalvendaexpedicao],
			foreignColumns: [table.id],
			name: "fk_nf_nfvendaexpedicao",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idcontacorrentedeposito],
			foreignColumns: [contacorrente.id],
			name: "fk_nf_contadeposito",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idcontacorrentepix],
			foreignColumns: [contacorrente.id],
			name: "fk_nf_contapix",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idlocalretirada],
			foreignColumns: [localretirada.id],
			name: "fk_nf_local_ret",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
		foreignKey({
			columns: [table.idplanocontas],
			foreignColumns: [planocontas.id],
			name: "fk_notafiscal_planocontas",
		})
			.onUpdate("cascade")
			.onDelete("set null"),
	],
);
