import {
	char,
	foreignKey,
	index,
	integer,
	numeric,
	pgTable,
	text,
	uniqueIndex,
	varchar,
} from "drizzle-orm/pg-core";
import { empresa } from "./empresas.js";

export const taxauf = pgTable(
	"taxauf",
	{
		id: text().primaryKey().notNull(),
		idempresa: text().notNull(),
		codigo: varchar({ length: 4 }).notNull(),
		descricao: text().notNull(),
		baseicms: numeric({ precision: 12, scale: 4 }),
		baseicmsfe: numeric({ precision: 12, scale: 4 }),
		baseicmsst: numeric({ precision: 12, scale: 4 }),
		uf_ac: numeric({ precision: 12, scale: 4 }),
		uf_al: numeric({ precision: 12, scale: 4 }),
		uf_am: numeric({ precision: 12, scale: 4 }),
		uf_ap: numeric({ precision: 12, scale: 4 }),
		uf_ba: numeric({ precision: 12, scale: 4 }),
		uf_ce: numeric({ precision: 12, scale: 4 }),
		uf_df: numeric({ precision: 12, scale: 4 }),
		uf_es: numeric({ precision: 12, scale: 4 }),
		uf_go: numeric({ precision: 12, scale: 4 }),
		uf_ma: numeric({ precision: 12, scale: 4 }),
		uf_mg: numeric({ precision: 12, scale: 4 }),
		uf_ms: numeric({ precision: 12, scale: 4 }),
		uf_mt: numeric({ precision: 12, scale: 4 }),
		uf_pa: numeric({ precision: 12, scale: 4 }),
		uf_pb: numeric({ precision: 12, scale: 4 }),
		uf_pe: numeric({ precision: 12, scale: 4 }),
		uf_pi: numeric({ precision: 12, scale: 4 }),
		uf_pr: numeric({ precision: 12, scale: 4 }),
		uf_rj: numeric({ precision: 12, scale: 4 }),
		uf_rn: numeric({ precision: 12, scale: 4 }),
		uf_ro: numeric({ precision: 12, scale: 4 }),
		uf_rr: numeric({ precision: 12, scale: 4 }),
		uf_rs: numeric({ precision: 12, scale: 4 }),
		uf_sc: numeric({ precision: 12, scale: 4 }),
		uf_se: numeric({ precision: 12, scale: 4 }),
		uf_sp: numeric({ precision: 12, scale: 4 }),
		uf_to: numeric({ precision: 12, scale: 4 }),
		baseiss: numeric({ precision: 12, scale: 4 }),
		iss: numeric({ precision: 12, scale: 4 }),
		pordif: numeric({ precision: 12, scale: 4 }).default("0"),
		bcporuf: char({ length: 1 }).default("N"),
		inativo: integer().default(0),
	},
	(table) => [
		index("taxauf_idempresa_idx").using(
			"btree",
			table.idempresa.asc().nullsLast().op("text_ops"),
		),
		uniqueIndex("taxauf_idempresa_codigo_uidx").using(
			"btree",
			table.idempresa.asc().nullsLast().op("text_ops"),
			table.codigo.asc().nullsLast().op("text_ops"),
		),
		foreignKey({
			columns: [table.idempresa],
			foreignColumns: [empresa.id],
			name: "taxauf_idempresa_fkey",
		})
			.onUpdate("cascade")
			.onDelete("cascade"),
	],
);
